### ISSUE TITLE
root view always shown even when token is set

### ISSUE THREAD

**Issue by crhuber** [itzikbenh/React-Native-on-Rails#1]
Thanks for the great tutorial. 
When the users token is already present on storage, for a brief section the root view of "login" or "register" is still shown until they are pushed to the home view. Is there any way to hide this or a way to improve the login flow so that users dont see these buttons when the app is first opened?

**Comment by itzikbenh** [comment]
No problem!
Currently I don't have time to add this change, but you can simply set the initial route based on if there is a valid token. 
At the moment I'm validating the token inside the 'root' view so you will always see it, even if for a short time. 

`  render() {
      return (
      <View style={styles.container}>
        <Navigator
          initialRoute={{name: 'root'}}
          renderScene={this.renderScene.bind(this)}
        />
      </View>
     );
   }`
Here is where the change needs to go. Add the token validation functionality to index.ios.js and use that to set the initial route.
